version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: rta_postgres
    environment:
      POSTGRES_USER: go_user
      POSTGRES_PASSWORD: go_pass
      POSTGRES_DB: analytics_db
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"   # ← Host:Container şeklinde; Docker içi 5432, host’ta 5433
    volumes:
      - rta_pgdata:/var/lib/postgresql/data

volumes:
  rta_pgdata:
